#!/bin/sh

# -----------------------------------------------------------------------------
# Yetamine OSGi Framework Launcher bootstrap script
#
# Environment variables can be used to set or override some parameters. Do not
# set the variables in this script. For specific deployment or application the
# variables should be rather set by the specific wrapper.
#
# JAVA
#   The command to launch JVM. Default assumes 'java' command available from
#   PATH.
#
# JAVA_OPTS
#   Additional Java runtime options passed to the JAVA command.
#
# YOFL_AUTOPATH
#   The path to the directory which shall be scanned for the .jar files to be
#   added to the boot class path.
#
# YOFL_BOOTPATH
#   The class path to be appended to the boot class path.
#
# YOFL_LOGGING_FILE
#   The desired output stream for the launcher logger. The value may be
#   'stdout' or 'stderr', which applies as the default, or a file name.
#
# YOFL_LOGGING_LEVEL
#   The logging level for the launcher logger.
#
# -----------------------------------------------------------------------------

# Resolve links ($0 may be a softlink)
RUNCMD="$0"

while [ -h "$RUNCMD" ]; do
  ls=`ls -ld "$RUNCMD"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    RUNCMD="$link"
  else
    RUNCMD=`dirname "$RUNCMD"`/"$link"
  fi
done

# Get standard environment variables
RUNDIR=`dirname "$RUNCMD"`

# OS specific support. All flag variables MUST be set to either true or false.
cygwin=false

case "`uname`" in
  CYGWIN*)  cygwin=true;;
  MINGW*)   cygwin=true;;
esac

# For Cygwin, switch paths to Unix format for the common processing
if $cygwin; then
  [[ -n "$YOFL_BOOTPATH" ]] && YOFL_BOOTPATH=`cygpath --path --unix "$YOFL_BOOTPATH"`
fi

# Set YOFL_HOME
YOFL_HOME=`cd "$RUNDIR" >/dev/null; pwd`
# Only set JAVA if not already set (then assuming 'java' is on PATH)
[[ -z "$JAVA" ]] && JAVA='java'
# The boot class path, which must be given explicitly when using -classpath
MAIN='net.yetamine.osgi.launcher.Main'
# Ensure that any user-defined CLASSPATH variables are not used and fill it
# with the argument to be used for --classpath anyway
CLASSPATH="${YOFL_HOME}/yofl.jar"
# Extend the class path with caller-defined entries
[[ -n "$YOFL_BOOTPATH" ]] && CLASSPATH="${CLASSPATH}:${YOFL_BOOTPATH}"

# Add modules from the boot/ directory
if [[ -n "$YOFL_AUTOPATH" ]]; then
    for file in "${YOFL_AUTOPATH}"/*.jar; do
      CLASSPATH="${CLASSPATH}:${file}"
    done
fi

# For Cygwin, switch paths to Windows format before running JAVA
if $cygwin; then
  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
fi

# Ensure the variables are exported
export YOFL_HOME

# Execute Java to launch the container
"$JAVA" $JAVA_OPTS "-Dnet.yetamine.osgi.launcher.logging.level=${YOFL_LOGGING_LEVEL}" "-Dnet.yetamine.osgi.launcher.logging.file=${YOFL_LOGGING_FILE}" -classpath "$CLASSPATH" "$MAIN" "$@"
